name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
          echo "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" | docker login ghcr.io -u RangaRathnayake --password-stdin
          docker build . --file Dockerfile --tag ghcr.io/rangarathnayake/loan-manage-back-nestjs:latest
          docker push ghcr.io/rangarathnayake/loan-manage-back-nestjs:latest
