name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
          echo "Lasa2012@Docker" | docker login -u RangaRathnayake --password-stdin
          docker build . --file Dockerfile --tag RangaRathnayake/loan-manage-back-nestjs:latest
          docker push RangaRathnayake/loan-manage-back-nestjs:latest
